# Generated by Django 4.2 on 2023-04-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_rename_user_id_todo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='user_id',
        ),
    ]
